#!/usr/bin/python3
# 100-print_tebahpla.py

"""Print the alphabet in reverse order alternating upper- and lower-case."""

for i in range(ord('z'), ord('a') - 1, -1):
    case = chr(i - 32) if i % 2 == 0 else chr(i)
    print(case, end="")
